TARGET = absolute leafyear passfail grade grade2 positive0negative bigLetter for one2ten multiplytable ascii star
all ss: $(TARGET)

absolute: $@
leafyear: $@
passfail: $@
grade: $@
grade2: $@
positive0negative: $@
bigLetter: $@
for: $@
one2ten:$@
multiplytable: $@
ascii: $@
star: $@

clean: 
	rm $(TARGET)