TARGET = swap selection bubble qsort pointaConcept endian pointa2 functionpointa voidpointer aa arrayAssignment arraycompare swapFunction sumArrayFunction sumMatrixFunction sumMatrixFunction2 serial hello3 characterPointerOperation strcatExample filePointer fileDescriptor

all: $(TARGET)
all ss: $(TARGET)

swap: $@
selection: $@
bubble: $@
qsort: $@
pointaConcept: $@
endian: $@
pointa2: $@
functionpointa: $@
voidpointer: $@
aa: $@
arrayAssignment: $@
arraycompare: $@
swapFunction: $@
sumArrayFunction: $@
sumMatrixFunction: $@
sumMatrixFunction2: $@
serial: $@
hello3: $@
characterPointerOperation: $@
strcatExample: $@
filePointer: $@
fileDescriptor: $@

clean: 
	rm $(TARGET)