TARGET = swap selection bubble qsort pointaConcept endian pointa2 functionpointa voidpointer aa arrayAssignment arraycompare swapFunction sumArrayFunction sumMatrixFunction sumMatrixFunction2
all ss: $(TARGET)

swap: $@
selection: $@
bubble: $@
qsort: $@
pointaConcept: $@
endian: $@
pointa2: $@
functionpointa: $@
voidpointer: $@
aa: $@
arrayAssignment: $@
arraycompare: $@
swapFunction: $@
sumArrayFunction: $@
sumMatrixFunction: $@
sumMatrixFunction2: $@

clean: 
	rm $(TARGET)