TARGET = infinit limit celsius2fahr fahr2celsius charNumber triangle triangle2 arithmetic increment literal genderratio compare compare2 sideof oddnum fourbit fourbit2


all ss: $(TARGET)

infinit : $@
limit : $@
celsius2fahr : $@
fahr2celsius : $@
characteNumber : $@
triangle:$@
triangle2:$@
arithmetic:$@
increment:$@
literal:$@
genderratio: $@
compare: $@
compare2: $@
sideof: $@
oddnum: $@
fourbit: $@
fourbit2: $@

clean :
	rm $(TARGET)

