TARGET = infinit limit celsius2fahr fahr2celsius charNumber triangle triangle2 arithmetic increment literal

all ss: $(TARGET)

infinit : $@
limit : $@
celsius2fahr : $@
fahr2celsius : $@
characteNumber : $@
triangle:$@
triangle2:$@
arithmetic:$@
increment:$@
literal:$@

clean :
	rm $(TARGET)

