TARGET = absolute leafyear passfail grade grade2 positive0negative bigLetter for one2ten multiplytable ascii star one2ten2 one2tendowhile randomTo100 staticlocalvariable functionexample returnValue power dice sumArray sumMatrix findmax scoreGrade proSCore average2022Temp alone baseball
all ss: $(TARGET)

absolute: $@
leafyear: $@
passfail: $@
grade: $@
grade2: $@
positive0negative: $@
bigLetter: $@
for: $@
one2ten:$@
multiplytable: $@
ascii: $@
star: $@
one2ten2: $@
one2tendowhile: $@
randomTo100: $@
staticlocalvariable: $@
functionexample: $@
returnValue: $@
power: $@
dice: $@
sumArray: $@
sumMatrix: $@	
findmax: $@
scoreGrade: $@
proSCore: $@
average2022Temp: $@
alone: $@
baseball: $@

clean: 
	rm $(TARGET)